---
name: Run beaker acceptance tests

on:
  workflow_dispatch:
    inputs:
      collection:
        description: |-
          (Collection) OpenVox collection to use. (ignored if Pre-release Build is true)

          NOTE: This should really only be set to openvox8 when
          testing the main branch. If you need to test openvox7, you
          should run the pipeline from the 7.x branch instead.
        default: 'openvox8'
        type: string

permissions:
  contents: read

env:
  RUBY_VERSION: '3.4.4'

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os:
          - [almalinux, '8']
          - [almalinux, '9']
    steps:
      - uses: actions/checkout@v4
      - name: Cleaning up the hypervisor
        shell: bash
        run: |
          for domain in $(virsh list --name | awk '/^test-/ {print $1}'); do
            virsh destroy $domain
            virsh undefine $domain --managed-save --remove-all-storage --delete-storage-volume-snapshots --wipe-storage --snapshots-metadata --checkpoints-metadata --nvram --tpm
          done
          if virsh net-list | grep -q test; then
            virsh net-destroy test
          fi
          if virsh net-list --inactive | grep -q test; then
            virsh net-undefine test
          fi
          # list all pools; list all volumes in pool; delete all volumes; delete all pools
          # this is a bit shitty; but libvirt creates the files as root:root and our github action runs as runner and I don't want to allow it to run sudo rm -rf /var/...
          for pool in $(virsh pool-list --name | awk '/.pool/ {print $1}'); do
            for vol in $(virsh vol-list --pool $pool); do
              virsh vol-delete $vol --pool $pool
            done
            virsh pool-destroy $pool
            virsh pool-undefine $pool
          done
      - id: vm-cluster
        uses: bastelfreak/nested_vms@reference-architecture
        with:
          os: ${{ matrix.os[0] }}
          os-version: ${{ matrix.os[1] }}
          os-arch: ${{ matrix.os[2] || 'x86_64' }}
          image_version: ${{ matrix.os[3] }}
          host-root-access: true
          ruby-version: ${{ env.RUBY_VERSION }}
          install-openvox: true
          github-runner: false
          debug: true
          vms: |-
            [
              {
                "role": "primary",
                "count": 1,
                "cpus": 8,
                "mem_mb": 4096,
                "cpu_mode": "host-model"
              },
              {
                "role": "agent",
                "count": 1,
                "cpus": 4,
                "mem_mb": 4096,
                "cpu_mode": "host-model"
              }
            ]
      # TODO replace with teardown plan
      - name: Deleting a cluster
        if: always()
        shell: bash
        run: |
          for domain in $(virsh list --name | awk '/^test-/ {print $1}'); do
            virsh destroy $domain
            virsh undefine $domain --managed-save --remove-all-storage --delete-storage-volume-snapshots --wipe-storage --snapshots-metadata --checkpoints-metadata --nvram --tpm
          done
          if virsh net-list | grep -q test; then
            virsh net-destroy test
          fi
          if virsh net-list --inactive | grep -q test; then
            virsh net-undefine test
          fi
          # list all pools; list all volumes in pool; delete all volumes; delete all pools
          # this is a bit shitty; but libvirt creates the files as root:root and our github action runs as runner and I don't want to allow it to run sudo rm -rf /var/...
          for pool in $(virsh pool-list --name | awk '/.pool/ {print $1}'); do
            for vol in $(virsh vol-list --pool $pool); do
              virsh vol-delete $vol --pool $pool
            done
            virsh pool-destroy $pool
            virsh pool-undefine $pool
          done
